namespace ChatBotAdmin.Models;

/// <summary>
/// Represents one continuous conversation a widget user has with a specific ChatBot.
/// Created by ChatBotServer on the first message and updated on every subsequent message.
/// </summary>
public class ChatSession
{
    public Guid Id { get; set; } = Guid.NewGuid();

    /// <summary>FK to the bot this session belongs to.</summary>
    public Guid DocumentChatBotId { get; set; }

    /// <summary>UUID generated by the widget and stored in sessionStorage — ties widget messages to this record.</summary>
    public string SessionToken { get; set; } = string.Empty;

    public DateTime StartedAt { get; set; } = DateTime.UtcNow;

    public DateTime LastActivityAt { get; set; } = DateTime.UtcNow;

    /// <summary>Total questions asked in this session (denormalised for quick list display).</summary>
    public int MessageCount { get; set; }

    /// <summary>Browser User-Agent string (optional, captured from request headers).</summary>
    public string? UserAgent { get; set; }

    /// <summary>Remote IP address (optional, captured from request headers).</summary>
    public string? IpAddress { get; set; }

    /// <summary>Name the user optionally provided in the widget greeting form.</summary>
    public string? UserName { get; set; }

    /// <summary>Email the user optionally provided in the widget greeting form.</summary>
    public string? UserEmail { get; set; }

    // Navigation
    public DocumentChatBot? DocumentChatBot { get; set; }
    public List<ChatMessage> Messages { get; set; } = [];
}
